default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') %>
  username: <%= ENV.fetch('DATABASE_USER') %>
  password: <%= ENV.fetch('DATABASE_PWD') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
  port: <%= ENV.fetch('DATABASE_PORT') %>

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_TEST_NAME') %>
  username: <%= ENV.fetch('DATABASE_TEST_USER') %>
  password: <%= ENV.fetch('DATABASE_TEST_PWD') %>
  host: <%= ENV.fetch('DATABASE_TEST_HOST') %>
  port: <%= ENV.fetch('DATABASE_TEST_PORT') %>

production:
  <<: *default
  database: in_parking_prod
  username: in_parking
  password: <%= ENV['DATABASE_PWD'] %>
