module Aws
    REGION = ENV['AWS_REGION']
    POOL_ID = ENV['AWS_COGNITO_USERS_POOL_ID']
    CLIENT_SECRET = ENV['AWS_COGNITO_USERS_CLIENT_SECRET']
    CLIENT_ID = ENV['AWS_COGNITO_USERS_CLIENT_ID']
    AUTH_FLOW = ENV['AWS_COGNITO_USERS_AUTH_FLOW']

    ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID']
    SECRET_ACCESS_KEY = ENV['AWS_SECRET_ACCESS_KEY']
end