# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: in_parking_test
          POSTGRES_USER: in_parking
          POSTGRES_PASSWORD: 123456
    env:
      RAILS_ENV: test
      APP_ENV: test
      DATABASE_TEST_PWD: "123456"
      DATABASE_TEST_USER: "in_parking"
      DATABASE_TEST_NAME: "in_parking_test"
      DATABASE_TEST_HOST: "localhost"
      DATABASE_TEST_PORT: "5432"
      DATABASE_PWD: "123456"
      DATABASE_USER: "in_parking"
      DATABASE_NAME: "in_parking"
      DATABASE_HOST: "localhost"
      DATABASE_PORT: "5432"
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: your_access_key_id
      AWS_SECRET_ACCESS_KEY: your_secret_access_key
      AWS_COGNITO_CONSUMERS_POOL_ID: your_pool_id
      AWS_COGNITO_CONSUMERS_CLIENT_ID: your_client_id
      AWS_COGNITO_LESSORS_POOL_ID: dummy
      AWS_COGNITO_LESSORS_CLIENT_ID: dummy
      AWS_COGNITO_USERS_AUTH_FLOW: dummy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load RAILS_ENV=test
      # Add or replace test runners here
      - name: Run tests
        run: bundle exec rspec
